### ISSUE TITLE
Dismiss()

### ISSUE THREAD

**Issue by Isabellle** [droidbyme/DroidDialog#2]
Hi and first of all, thank you for your awesome library.
I put the DroidDialog in a runOnUiThread, but I don't know how to dismiss it onPause() for instance.
Thanks for any help;

**Comment by Isabellle** [comment]
Or do you have another method to "kill" it ? Thanks

**Comment by lutsifer** [comment]
Almost same problem here, I am trying to implement dialog.dismiss() after 20 sec.
Any ideas?

**Comment by lutsifer** [comment]
@Isabellle there is simple workaround for this:
` Dialog dialog = null;
    public DroidDialog(final DroidDialog.Builder builder) {
        dialog = new Dialog(builder.context);
.....
}
public void close(){
        dialog.dismiss();
    }
`
Then you call it as DroidDialog myDialog = new DroidDialog(....);
and you already have close();

**Comment by lutsifer** [comment]
Of course you have to create your own class to implement it. It would be very nice if someone incorporate this code inside repo.

**Comment by droidbyme** [comment]
@lutsifer correct one. Do as lutsifer say.. As normal dialog, same happening..

**Comment by droidbyme** [comment]
compile 'com.github.droidbyme:DroidDialog:d4b5af0f48'

I upgrade DroidDialog library with dismiss() method.. Use above dependency to get dismiss method for DroidDialog.. Thanks to all..

**Comment by lutsifer** [comment]
I just decided you are a bit **lazy** person :) Thanks!
